[heatmap_transform]
roi_size = [368, 64, 320]
spacing = true
overlap = 0.6

[centerline_transform]
step_size = 50
threshold = 100
spatial_threshold = 5

[polar_transform]
n_angles = 31
polar_ray = 127
cartesian_ray = 100
length = 7
multiple_centers = false
annotation_resolution = 100

[contour_transform]
dropout = false
n_repeats = 20
delta_theta = 0.0625  # Fraction of the circle
single_center = false
interpolation_method = "polynomial"
split_list = []

[segmentation_transform]