[heatmap_transform]
roi_size = [64, 64, 160]
spacing = true

[centerline_transform]
step_size = 50
threshold = 100
spatial_threshold = 5

[polar_transform]
n_angles = 31
polar_ray = 127
cartesian_ray = 100
length = 7
multiple_centers = false

[contour_transform]
eval_mode = "eval"
n_repeats = 20
delta_theta = 0.0625

[segmentation_transform]