stages:
  - functional-test

functional-test:
  image: python:3.9.7
  stage: functional-test
  before_script:
    - pip install -e ./src
    - make prepare-test
  script:
    - coverage run -m pytest
    - coverage report
    - coverage xml
  coverage: '/(?i)total.*? (100(?:\.0+)?\%|[1-9]?\d(?:\.\d+)?\%)$/'
  artifacts:
    reports:
      coverage_report:
        coverage_format: cobertura
        path: coverage.xml
