stages:
  - src-test
  - docs

src-test:
  image: python:3.10.11
  stage: src-test
  before_script:
    - pip install -e ./src
    - make prepare-test
  script:
    - coverage run -m pytest
    - coverage report
    - coverage xml
  coverage: '/(?i)total.*? (100(?:\.0+)?\%|[1-9]?\d(?:\.\d+)?\%)$/'
  artifacts:
    reports:
      coverage_report:
        coverage_format: cobertura
        path: coverage.xml

docs:
  image: python:3.9.7
  stage: docs
  before_script:
    - pip install -r ./docs/requirements.txt
  script:
    - mkdocs build --clean --site-dir html --config-file mkdocs.yml
