stages:
  - functional-test

functional-test:
  image: python:3.9.7
  stage: functional-test
  before_script:
    - pip install -e ./src
    - make get-reference
  script:
    - pytest ./tests/unit_tests
    - pytest ./tests/test_cli.py
    - pytest ./tests/heatmap_transform/test_heatmap_transform.py
    - pytest ./tests/centerline_transform/test_centerline_transform.py
    - pytest ./tests/polar_transform/test_polar_transform.py
    - pytest ./tests/contour_transform/test_contour_transform.py
    - pytest ./tests/segmentation_transform/test_segmentation_transform.py
