stages:
  - test

test:
  image: python:3.9.7
  stage: test
  before_script:
    - pip install numpy==1.22.4
    - pip install -e ./src
  script:
    - pytest ./tests/test_cli.py
    - pytest ./tests/heatmap_transform/test_heatmap_transform.py
    - pytest ./tests/centerline_transform/test_centerline_transform.py
    - pytest ./tests/polar_transform/test_polar_transform.py
    - pytest ./tests/segmentation_transform/test_segmentation_transform.py
