variables:
  DOCKER_HOST: tcp://docker:2375/

stages:
  - debug
  - build
  - test

find-docker-port:
  image: alpine
  stage: debug
  services:
    - docker:dind
  script:
    - apk add nmap
    - nmap -sT -p- docker

build:
  services:
    - docker:dind
  stage: build
  image: docker:latest
  before_script:
    - cp -r ./tests/models .
  script:
    - docker build -t carotidsegmentation .

test:
  image: python:3.9.7
  stage: test
  before_script:
    - pip install numpy==1.22.4
    - pip install -e ./src
  script:
    - pytest ./tests/test_cli.py
    - pytest ./tests/heatmap_transform/test_heatmap_transform.py
    - pytest ./tests/centerline_transform/test_centerline_transform.py
    - pytest ./tests/polar_transform/test_polar_transform.py
    - pytest ./tests/segmentation_transform/test_segmentation_transform.py
