# .readthedocs.yaml
# Read the Docs configuration file
# See https://docs.readthedocs.io/en/stable/config-file/v2.html for details

# Required
version: 2

# Set the version of Python and other tools you might need
build:
  os: ubuntu-22.04
  tools:
    python: "3.9.7"
  jobs:
    post_create_environment:
      # Install docs group of dependencies
      - pip install -r ./docs/requirements.txt

mkdocs:
  configuration: mkdocs.yml
